### ISSUE TITLE
Export of localization results

### ISSUE THREAD

**Issue by Werkov** [Werkov/dove-eye#2]
Currently they're just drawn in the QGLViewer, and printed to stderr/stdout. Apart from any complex GUI changes (like selecting subset of trajectory to be saved), this issue would be solved by allowing storing the data in  a text file.

**Comment by JankaSvK** [comment]
https://github.com/JankaSvK/dove-eye/commit/47fa8880167ae66e55bf1ee55b796c3f60204fb8

Exporting as XML or YAML.

**Comment by Werkov** [comment]
Thanks! Closing the issue.
